trainer:
  gpus: -1
  accelerator: 'ddp'
#  fast_dev_run: 5
  # precision: 16
data:
  batch_size: 16
  shuffle: True
#  num_workers: None
  samples: None
  drop_last: True
logger:
  project: draft-sentiment-5


