# Generated by Django 4.1.4 on 2022-12-17 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linguistic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
    ]
