# Generated by Django 4.1.4 on 2022-12-17 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("linguistic", "0002_article"),
    ]

    operations = [
        migrations.CreateModel(
            name="Collection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
            ],
        ),
    ]
