# Generated by Django 4.1.4 on 2022-12-17 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("linguistic", "0003_collection"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="text",
            field=models.TextField(default=""),
        ),
    ]
