on:
  pull_request:
    branches: [ core ]

jobs:
  build:
    name: Try Build Underthesea Core
    if: "!contains(github.event.head_commit.message, 'Publish Underthesea Core')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v4
      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          curl -sSL https://install.python-poetry.org | python -
      - name: Add poetry to path
        run: echo "${HOME}/.poetry/bin" >> $GITHUB_PATH
      - name: Install package deps
        working-directory: ./extensions/underthesea_core
        run: |
          poetry install
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - name: Build Python package
        working-directory: ./extensions/underthesea_core
        run: poetry run maturin develop --release
