on:
  pull_request:
    branches: [ main ]
    types:
      - labeled
      - synchronize

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get PR Labels
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_LABELS=$(gh pr view https://github.com/${{ github.repository }}/pull/${{ github.event.pull_request.number }} --json labels --jq '[.labels[].name]')
          echo "$PR_LABELS"
          echo "PR_LABELS=$PR_LABELS" >> $GITHUB_ENV
      - name: Set up Python 3.7
        if: contains(env.PR_LABELS, 'ci-prompt') || github.event.action == 'synchronize'
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install dependencies and Run tests
        if: contains(env.PR_LABELS, 'ci-prompt') || github.event.action == 'synchronize'
        run: |
          python -m pip install --upgrade pip
          pip install pytest tox
          tox -e prompt

