on:
  pull_request:
    branches: [ master ]

jobs:
  ci:
    if: "contains(github.event.head_commit.message, 'ci sentiment')"
    name: Training sentiment model
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
