on:
  push:
    branches: [ core ]

jobs:
  macos-arm-build-pypi-publish:
    name: "Run MacOS"
    if: "contains(github.event.head_commit.message, 'Test Self Hosted')"
    runs-on: macos-arm64
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install poetry
        working-directory: ./extensions/underthesea_core
        run: |
          mkdir "${PWD}/poetry"
          curl -sSL https://install.python-poetry.org | POETRY_HOME=${PWD}/poetry python -
      - name: Install package deps
        working-directory: ./extensions/underthesea_core
        env:
          MATURIN_PASSWORD: ${{ secrets.PYPI_UNDERTHESEA_CORE_API_TOKEN }}
        run: |
          # add poetry to path
          export PATH="${PWD}/poetry/bin:${PATH}"
          poetry install
          poetry run maturin build --release --no-sdist --strip --interpreter python
          find ./target/wheels/
          poetry run maturin publish --username __token__ --no-sdist --interpreter python
          ls
