on:
  push:
    branches: [ core ]

jobs:
  macos-arm-build-pypi-publish:
    name: "Run MacOS"
    if: "contains(github.event.head_commit.message, 'Test Self Hosted')"
    runs-on: macos-arm64
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
 